name: CI
on:
  push:
    branches:
      - main
  pull_request:
permissions:
  contents: read
jobs:
  lint-and-test:
    name: Lint and Test (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout go-tf
        uses: actions/checkout@v7.0.1
      - name: Normalize line endings to LF
        run: |
          git config --local core.autocrlf false
          git config --local core.eol lf
          git reset --hard HEAD
      - name: Setup Go
        uses: actions/setup-go@v7.0.0
        with:
          go-version-file: go.mod
      - name: Install yamlfmt
        run: |
          echo "$(go env GOPATH)/bin" >> "$GITHUB_PATH"
          go install github.com/google/yamlfmt/cmd/yamlfmt@latest
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v9.3.0
        with:
          version: latest
      - name: Run markdownlint
        uses: DavidAnson/markdownlint-cli2-action@v24.2.0
        with:
          globs: "**/*.md"
      - name: Run yamlfmt lint
        run: make lint-yaml
      - name: Run unit test
        run: make test
