name: CI
on:
  push:
    branches:
      - main
  pull_request:
permissions:
  contents: read
jobs:
  lint:
    name: Lint (ubuntu-latest)
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout go-tf
        uses: actions/checkout@v7.0.1
      - name: Setup Go
        uses: actions/setup-go@v7.0.0
        with:
          go-version-file: go.mod
      - name: Setup Node
        uses: actions/setup-node@v7.0.0
        with:
          node-version: "22"
      - name: Install yamlfmt
        run: |
          echo "$(go env GOPATH)/bin" >> "$GITHUB_PATH"
          go install github.com/google/yamlfmt/cmd/yamlfmt@latest
      - name: Install markdownlint-cli2
        run: npm install -g markdownlint-cli2
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v9.3.0
        with:
          version: latest
      - name: Run lint
        run: make lint
  unit-test:
    name: Unit Test (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout go-tf
        uses: actions/checkout@v7.0.1
      - name: Setup Go
        uses: actions/setup-go@v7.0.0
        with:
          go-version-file: go.mod
      - name: Run unit test
        run: make test
